AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IapVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: "IAP-VPC"

  IapInternetGateway:
    Type: "AWS::EC2::InternetGateway"

  IapVPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref IapVPC
      InternetGatewayId: !Ref IapInternetGateway

  IapSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref IapVPC
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: "ap-south-1a"
      Tags:
        - Key: Name
          Value: "IAP-Subnet"

  IapRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref IapVPC
      Tags:
        - Key: Name
          Value: "IAP-RouteTable"

  IapRoute:
    Type: "AWS::EC2::Route"
    DependsOn: IapVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref IapRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref IapInternetGateway

  IapSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref IapSubnet
      RouteTableId: !Ref IapRouteTable

  IapSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security Group for Resources"
      VpcId: !Ref IapVPC

  IapEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref IapSecurityGroup
      SubnetId: !Ref IapSubnet
      ImageId: "ami-0607784b46cbe5816" 
      KeyName: "awskey" 
      Tags:
        - Key: Name
          Value: "IAP-EC2Instance"

  IapS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "iapbucket3391"